### ISSUE TITLE
how to implement the mbtiles

### ISSUE THREAD

**Issue by nrb1238** [bertt/Mapsui.Forms#1]
@bertt 
Can we implement the mbtiles use this package? if yes can you please help me out on it?

**Comment by bertt** [comment]
Hi, yes this should work. Technically, the MBTile is just an SQLite database. So install package sqlite-net-pcl (https://www.nuget.org/packages/sqlite-net-pcl) in all projects and then use MbTilesProvider from BruTile.
Disclaimer: Haven't tried this yet (only used SQLite database in Xamarin.Forms project)
